# SPDX-FileCopyrightText:  pypsa-kz-data authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "kz_default_2013" # use this to keep track of runs with different settings

scenario:
  opts: [1H]

snapshots:
  start: "2013-01-01"
  end: "2014-01-01"

load_options:
  weather_year: 2013  # Load scenarios available with different weather year (different renewable potentials)

atlite:
  cutouts:
    asia-2013-era5:
      module: era5
      dx: 0.3  # cutout resolution
      dy: 0.3  # cutout resolution

renewable:
  onwind:
    cutout: asia-2013-era5
  offwind-ac:
    cutout: asia-2013-era5
  offwind-dc:
    cutout: asia-2013-era5
  solar:
    cutout: asia-2013-era5
  hydro:
    cutout: asia-2013-era5
    normalization:
      year: 2013
