# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "kz_2011_discount20" # use this to keep track of runs with different settings

snapshots:
  start: "2011-01-01"
  end: "2012-01-01"

load_options:
  weather_year: 2011  # Load scenarios available with different weather year (different renewable potentials)

electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc]
    Store: [battery, H2]

atlite:
  cutouts:
    asia-2011-era5:
      module: era5
      dx: 0.3  # cutout resolution
      dy: 0.3  # cutout resolution

renewable:
  onwind:
    cutout: asia-2011-era5
  offwind-ac:
    cutout: asia-2011-era5
  offwind-dc:
    cutout: asia-2011-era5
  solar:
    cutout: asia-2011-era5
  hydro:
    cutout: asia-2011-era5
    normalization:
      year: 2011

costs:
  fill_values:
    discount rate: 0.2

